# Generated by Django 5.0.6 on 2024-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
    ]
