# Generated by Django 5.0.6 on 2024-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
