# Generated by Django 5.0.6 on 2024-05-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_herosection1_heroimage1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage1',
            name='hero_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herofirstimages', to='app.herosection1'),
        ),
    ]
