# Generated by Django 5.0.6 on 2024-05-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
