# Generated by Django 5.0.6 on 2024-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
