# Generated by Django 5.0.6 on 2024-06-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_order_quantity_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
