# Generated by Django 5.0.6 on 2024-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
