# Generated by Django 5.0.6 on 2024-05-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
