# Generated by Django 5.0.6 on 2024-05-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_name_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='about',
        ),
    ]
