# Generated by Django 5.0.6 on 2024-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default='22', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
